---
title: "Demonstrating Genetic Regulation in SignalGP - Analysis - Changing Signal Task"
output: 
  html_document: 
    keep_md: no
    toc: true
    toc_float: true
    toc_depth: 4
    collapsed: false
    theme: default
    code_folding: hide
  pdf_document:
    toc: true
    toc_depth: 4
---

## Overview

## Dependencies

Load all required R libraries.

```{r, message=FALSE}
library(ggplot2)  # (Wickham, 2009)
library(dplyr)    # (Wickham et al., 2018)
library(cowplot)  # (Wilke, 2018)
library(viridis)  # (Garnier, 2018)
```

## Setup

Load data, initial data cleanup, global settings.

```{r}
data_loc <- "../data/chg-env/rd2/max_fit_orgs.csv"
data <- read.csv(data_loc, na.strings="NONE")

# Specify factors.
data$matchbin_thresh <- factor(data$matchbin_thresh,
                               levels=c(0, 25, 50, 75))
data$NUM_ENV_STATES <- factor(data$NUM_ENV_STATES,
                              levels=c(2, 4, 8, 16, 32))
data$NUM_ENV_UPDATES <- factor(data$NUM_ENV_UPDATES,
                               levels=c(2, 4, 8, 16, 32))
data$TAG_LEN <- factor(data$TAG_LEN,
                       levels=c(32, 64, 128))
# Define function to summarize regulation/memory configurations.
get_con <- function(reg, mem) {
  if (reg == "0" && mem == "0") {
    return("none")
  } else if (reg == "0" && mem=="1") {
    return("memory")
  } else if (reg=="1" && mem=="0") {
    return("regulation")
  } else if (reg=="1" && mem=="1") {
    return("both")
  } else {
    return("UNKNOWN")
  }
}
# Specify experimental condition for each datum.
data$condition <- mapply(get_con, data$USE_FUNC_REGULATION, data$USE_GLOBAL_MEMORY)
data$condition <- factor(data$condition, levels=c("regulation", "memory", "none", "both"))


# Settings for statistical analyses.
alpha <- 0.05
correction_method <- "bonferroni"
```

## How many solutions evolve?

### Number of evolved solutions per condition

An organism is categorized as a 'solution' if it can correctly respond in each of the $K$ environment states.

```{r, echo=TRUE}

label_lu <- c(
  "2" = "2 Environments", 
  "4" = "4 Environments", 
  "8" = "8 Environments", 
  "16" = "16 Environments", 
  "32" ="32 Environments"
)

# melted <- melt(filter(data, condition=="both"),
#                variable.name = "solution_type",
#                value.name = "solution_val",
#                measure.vars=c("solution", "all_solution", "all_solution_ko_reg"))
# Grab count data to make bar plot life easier
num_solutions <- length(filter(data, 
                               condition=="both" & solution=="1")$SEED)
num_generalize <- length(filter(data, 
                                condition=="both" & all_solution=="1")$SEED)
num_generalize_ko_reg <- length(filter(data, condition=="both" &
                                              all_solution_ko_reg=="1")$SEED)
num_generalize_mem <- length(filter(data, condition=="memory" & all_solution=="1")$SEED)

sol_cnts <- data.frame(x=1:3)
sol_cnts$type <- c("reg_generalize", "reg_generalize_ko_reg", "mem_generalize")
sol_cnts$val <- c(num_generalize, num_generalize_ko_reg, num_generalize_mem)

ggplot(sol_cnts, aes(x=type, y=val, fill=type)) +
  geom_bar(stat="identity") +
  geom_text(aes(label=val), 
            stat="identity",
            position=position_dodge(0.75), vjust=-0.01) +
  scale_x_discrete(name="Condition",
                   limits=c("mem_generalize", "reg_generalize", "reg_generalize_ko_reg"),
                   labels=c("Memory", "Reg.", "Reg.\n(knockouts)")) +
  scale_y_continuous(name="Generalize",
                     limits=c(0, 110),
                     breaks=seq(0,100,20)) +
  theme(legend.position="none",
        axis.text.x = element_text(size=10)) +
  # coord_flip() +
  ggsave("./imgs/chg-env-16-generalization.pdf", width=4,height=3)
```