---
title: "Regulation Type Exploration"
output: 
  pdf_document:
    toc: true
    toc_depth: 4
  html_document: 
    keep_md: yes
    toc: true
    toc_float: true
    toc_depth: 4
    collapsed: false
    theme: default
---

```{r, message=FALSE}
library(tidyr)    # (Wickham & Henry, 2018)
library(ggplot2)  # (Wickham, 2009)
library(plyr)     # (Wickham, 2011)
library(dplyr)    # (Wickham et al., 2018)
library(cowplot)  # (Wilke, 2018)
```


```{r}
data_loc <- "../data/max_fit_orgs.csv"
data <- read.csv(data_loc, na.strings="NONE")

data$matchbin_thresh <- factor(data$matchbin_thresh,
                                     levels=c(0, 25, 50, 75))
data$matchbin_regulator <- factor(data$matchbin_regulator,
                                     levels=c("add", "mult"))
data$NUM_SIGNAL_RESPONSES <- factor(data$NUM_SIGNAL_RESPONSES,
                                     levels=c(4, 8, 16, 32))
```

```{r}
# SEED mbin_metric mbin_thresh NUM_SIGNAL_RESPONSES MUT_RATE__FUNC_TAG_BF score
ggplot(data, aes(x=matchbin_regulator, y=score, color=matchbin_regulator)) +
  geom_boxplot() +
  facet_wrap(~ NUM_SIGNAL_RESPONSES, scales="free_y")
  # ggsave("plot.pdf", width=16, height=8)
```

```{r}
# SEED mbin_metric mbin_thresh NUM_SIGNAL_RESPONSES MUT_RATE__FUNC_TAG_BF score
ggplot(data, aes(x=matchbin_regulator, y=solution, fill=matchbin_regulator)) +
  geom_bar(stat="identity") +
  facet_wrap(~ NUM_SIGNAL_RESPONSES, scales="free_y")
  # ggsave("plot.pdf", width=16, height=8)
```