---
title: "Mutation Rate Exploration"
output: 
  pdf_document:
    toc: true
    toc_depth: 4
  html_document: 
    keep_md: yes
    toc: true
    toc_float: true
    toc_depth: 4
    collapsed: false
    theme: default
---

```{r, message=FALSE}
library(tidyr)    # (Wickham & Henry, 2018)
library(ggplot2)  # (Wickham, 2009)
library(plyr)     # (Wickham, 2011)
library(dplyr)    # (Wickham et al., 2018)
library(cowplot)  # (Wilke, 2018)
```


```{r}
data_loc <- "../hpcc/mut-rate-exps/data/max_fit_orgs.csv"
data <- read.csv(data_loc, na.strings="NONE")

data$MUT_RATE__FUNC_TAG_BF <- factor(data$MUT_RATE__FUNC_TAG_BF,
                                     levels=c(5e-04, 1e-03, 2e-03, 5e-03))
data$mbin_thresh <- factor(data$mbin_thresh,
                                     levels=c("-1/1","7/4","5/4"))
```

```{r}
# SEED mbin_metric mbin_thresh NUM_SIGNAL_RESPONSES MUT_RATE__FUNC_TAG_BF score
ggplot(data, aes(x=MUT_RATE__FUNC_TAG_BF, y=score, color=mbin_metric)) +
  geom_boxplot() +
  facet_grid(NUM_ENV_CYCLES ~ mbin_thresh, scales="free_y") + 
  ggsave("plot.pdf", width=16, height=8)
```